/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class App {

    public static void main(String[] args) {

        LinkedList myList = new LinkedList();
        myList.insert(8);
        myList.insert(9);
        myList.insert(2);
        myList.insert(5);
        Node current = myList.head;

        while (current != null) {
            System.out.println(current.value);
            current = current.next;
        }

        System.out.println(myList.includes(8));
        System.out.println(myList.includes(3));
        System.out.println(myList.includes(5));
        System.out.println(myList.includes(10));

        System.out.println(myList.toString());
    }
}